### PR TITLE
fix(EU): correction to get total power consumed from driving info

### PR DESCRIPTION
**Pull request by WillemD61**
total power consumed is obtained from drivingInfo, not drivingInfoDetail

### CODE REVIEW

**Comment by cdnninja** [comment]
@ZuinigeRijder could you review this? I think this may impact your integration.

**Comment by ZuinigeRijder** [comment]
> @ZuinigeRijder could you review this? I think this may impact your integration.

I will have a closer look later today or tomorrow.

**Review by ZuinigeRijder — COMMENTED** [review]
I would expect on line 1038 an extra check to avoid an error on possibly missing drivingInfoDetail:
     if get_child_value(responseAlltime, "resMsg.drivingInfoDetail.0"):

**Comment by WillemD61** [comment]
I assume you want to have that check so that the calculation of daily driving stats that follows is succesfull.

But therefore you will have to test for presence of drivingInfoDetail in the response30d, not in the responseAlltime.

So line 1038 should be
if get_child_value(response30d, "resMsg.drivingInfoDetail.0"):
And line 1039 to 1050 should be subject to this condition.

If agreed, I will make the additional change in this PR.

**Comment by WillemD61** [comment]
adjusted now included extra if statement

**Review by ZuinigeRijder — APPROVED** [review]

**Review by fuatakgun — APPROVED** [review]
LGTM

**Pull request merged**
