### PR TITLE
fix: Distance unit fixed

### PR DESCRIPTION
**Pull request by Bubo08**
Should fix the kia_uvo problem: Not valid unit for device class distance #812

### CODE REVIEW

**Comment by cdnninja** [comment]
This should match the property approach of the rest of the file with a setter. On my phone so hard to link to an example but I can later.

**Comment by cdnninja** [comment]
Here is an example of unit being used.

Values being stored here: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/2ca8b233c0c012d702f511702bb40991914f42c1/hyundai_kia_connect_api/Vehicle.py#L143-L145

and setter getter: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/2ca8b233c0c012d702f511702bb40991914f42c1/hyundai_kia_connect_api/Vehicle.py#L258-L266

Plus from the EU API this must be set correctly.

**Review by cdnninja — CHANGES_REQUESTED** [review]
Marking as requested changes per above.

**Comment by Bubo08** [comment]
I took the following code as template as the odometer is not throwing this kind of error:

    @property
    def odometer(self):
        return self._odometer

    @property
    def odometer_unit(self):
        return self._odometer_unit

    @odometer.setter
    def odometer(self, value):
        float_value = get_float(value[0])
        self._odometer_value = float_value
        self._odometer_unit = value[1]
        self._odometer = float_value

Therefore I thought the unit setter function is missing and I added them. Why do you think this is not correct?

**Comment by cdnninja** [comment]
Oops you are correct. The rest was in before this PR.

**Pull request merged**
