### PR TITLE
fix(USA): Change Climate Data for EV

### PR DESCRIPTION
**Pull request by zphaze**
Change data for EV climate start to match sniffed data from iOS app

### CODE REVIEW

**Comment by cdnninja** [comment]
Yup! This looks great! Have you tried running this locally? 

If not a fast way to test this is with python and GitHub desktop locally.

**Comment by zphaze** [comment]
Got it running on my local machine and it was still giving errors until I made the casting change inside airtemp and defrost. Once that change is made it called successfully and my car started.

**Comment by cdnninja** [comment]
The casting could be your input type?  Maybe we merge without casting and try home assistant? 

Casting like this is often what you passed into the calling command needed casting up front.

**Comment by zphaze** [comment]
You are right, It looks like as long at the set_temp is passed as a string the command works tho. We can definitely merge without the casting and see how home assistant passes that data

```
>>> i5.set_temp = '72'
>>> vm.start_climate('vehicle_id', i5)
hyundai_kia_connect_api - Start engine data: {'airCtrl': 1, 'airTemp': {'value': '72', 'unit': 1}, 'defrost': False, 'heating1': 0}
hyundai_kia_connect_api - Start engine response: 
>>> i5.set_temp = 72
>>> vm.start_climate('vehicle_id', i5)
hyundai_kia_connect_api - Start engine data: {'airCtrl': 1, 'airTemp': {'value': 72, 'unit': 1}, 'defrost': False, 'heating1': 0}
hyundai_kia_connect_api - Start engine response: {"errorSubCode":"GEN","systemName":"HATA","functionName":"remoteFATCStart","errorSubMessage":"HATA remoteFATCStart service failed while performing the operation RemoteFATCStart","errorMessage":"We're sorry, but we could not complete your request. Please try again later.","errorCode":502,"serviceName":"RemoteFATCStart"}
```

**Comment by zphaze** [comment]
Error still occurring, looks like home assistant passes air_temp as a float instead of a string

**Pull request merged**
