### PR TITLE
fix(EU): force update

### PR DESCRIPTION
**Pull request by jwefers**
I realized that force update is not implemented or at least does not update any internal state. This implements the forced update
by first retrieving either the cached state or the full forced state (as bluelinky does) and then updates the internal properties from the pieced-together dict.

It also implements a `_get_location` method, cdnninjas is more fleshed out though

### CODE REVIEW

**Comment by CreasolTech** [comment]
I hope these patches are integrated in the master branch soon.

**Comment by CreasolTech** [comment]
Very nice work!
I'm using lib taken from https://github.com/jwefers/hyundai_kia_connect_api and I can confirm that it works perfectly.
I'm using with Domoticz plugin https://github.com/CreasolTech/domoticz-hyundai-kia and location/speed/odometer/... update perfectly, now. Hope this patch will be merged soon!

**Comment by CreasolTech** [comment]
Hi, I found an issue when asking for vehicle refresh and the vehicle has data connection broken:
when I call 

vm.force_refresh_all_vehicles_states()

after about 240s I get

hyundai_kia_connect_api - _get_location failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 80, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/VehicleManager.py", line 84, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 184, in force_refresh_vehicle_state
    self._update_vehicle_properties(vehicle, state)
  File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 187, in _update_vehicle_properties
    vehicle.last_updated_at = self.get_last_updated_at(
  File "/usr/local/lib/python3.9/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 162, in get_last_updated_at
    m = re.match(r"(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})", value)
  File "/usr/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
>>> 

Thanks a lot

**Comment by jwefers** [comment]
thanks for discovering :) i will read through it probably on the weekend. maybe simply using cdnninjas version (other pr) takes care of this already

**Comment by cdnninja** [comment]
Previously when we use this for the kia_uvo integration we call the get cached status after a force update.  I will take a closer look at this and provide feedback.

**Comment by jwefers** [comment]
okay now that i read through it - i mean if the api simply does not respond sometimes - only thing we could do is add a timelimit for the request

**Comment by cdnninja** [comment]
I am getting back into this.  Taking a look I think this makes alot of sense.    I think next steps though is implementing and updating this for other regions.  I have alot going on with getting this API ready for prime time on the kia_uvo version 2.0 home assistant integration. Lots of commits coming.   Feel free to tweak this if you have time. If not I will get to it soon as this may be related to another bug I have in kia_uvo.

**Comment by jwefers** [comment]
Hi,
unfortunately i am out till end of year. too many other responsibilities until then. but in january, i probably can spend time again

**Pull request merged**
