### PR TITLE
fix: add requirements from requirements.txt

### PR DESCRIPTION
**Pull request by fhempy**
Hi,

the setup.py file is missing a lot of the requirements from requirements.txt. I updated the code to include all the requirements from requirements.txt.

### CODE REVIEW

**Comment by fhempy** [comment]
I just saw that there are too many requirements in the requirements.txt document. It would make sense to cleanup requirements.txt before merge.

As I'm not sure which workflows rely on the requirements.txt I didn't change anything there. Would be great if someone could have a look at it. Thx!

**Comment by cdnninja** [comment]
Do you mean you see some that aren't used?  Not sure what you mean by too many.

**Comment by fhempy** [comment]
requirements.txt normally includes only the packages which are required for the installation. In this case it includes things like coverage, pytest, flake8, etc.. This should be only included in the requirements_dev.txt I think.

**Comment by cdnninja** [comment]
I have shrunk the list by a good bit.   It could probably go a bit further. Could you review and let me know if you are okay with me merging this?

**Comment by fhempy** [comment]
Thanks for the cleanup! I would say that following dependencies could be removed as well
```
Click==8.1.3
watchdog==3.0.0
```
I searched the source code but couldn't find an import of those.

**Comment by cdnninja** [comment]
Done! I will merge now.

**Comment by fhempy** [comment]
Great, thx!

**Pull request merged**
