### PR TITLE
feat: China region support

### PR DESCRIPTION
**Pull request by toraidl**
Add initial support for Bluelink&Kia Connect

| Features | BlueLink | Kia |
| :--: | :--: | :--:|
|Sigin | ✅|✅|
|Climate on/off  | ✅ |not tested|
|Door lock/unlock | ✅ |not tested|
|Vehicle Status | ✅ |not tested|

Other features needed to be tested, as Sonata being used only has limited features available.

### CODE REVIEW

**Comment by cdnninja** [comment]
This is awesome! Thank you so much for doing this.  

I'll take a read through this and provide any feedback in the coming days.

**Comment by toraidl** [comment]
Thank you!
The Bluelink API here is very similar to the EU , so the codes are basically the same as KiaUvoApiEU.py
There are only minor differences, such as  authorization part, and vehicle status response json data structure.
 
Based on the captured HTTPS traffic, it appears that the latest version of the Bluelink app uses the V2 API to both fetch the status of  and control the vehicle. 
However, V1 API is still working and has not been abandoned yet. 

Please take your time to go through the ontent and let me know if you have any questions or feedback.

**Comment by zulufoxtrot** [comment]
Looks good to me. 👍

**Comment by toraidl** [comment]
@fuatakgun  That sounds promising. Initially, my plan was to inherit the EU version, but since I'm not very familiar with Python, I was concerned about introducing bugs. As a result, I opted for the easiest approach.

**Comment by cdnninja** [comment]
As a whole looks good!  For the tests to work you would need to add your username and password as a secret to this repository.   It does have a certain level of risk.  Your call if you would like to do that.  If not the test will need to be removed.

**Comment by cdnninja** [comment]
Are you a home assistant user? I plan to add this region to the ha integration and someone to test or assist would be great!

**Comment by toraidl** [comment]
> Are you a home assistant user? I plan to add this region to the ha integration and someone to test or assist would be great!

Yes, I am HA user.

**Comment by LitchiCherry** [comment]
是不是新车型默认只能用新的api，导致现在无法登录

**Pull request merged**
