### PR TITLE
feat(EU): Driving info

### PR DESCRIPTION
**Pull request by cdnninja**

### CODE REVIEW

**Comment by zulufoxtrot** [comment]
Tested (Kia Eu), it works.
However, I feel like we could use more data from this endpoint, such as daily consumption/regen stats.
I have a working prototype, maybe I can submit a PR after this one is merged.

**Review by zulufoxtrot — CHANGES_REQUESTED** [review]

**Comment by cdnninja** [comment]
> Tested (Kia Eu), it works. However, I feel like we could use more data from this endpoint, such as daily consumption/regen stats. I have a working prototype, maybe I can submit a PR after this one is merged.

How about you submit yours instead?  This one is being created so I can re-create a feature on kia_uvo but haven't had time to refine.  Having someone who can test as they write is amazing!

**Comment by zulufoxtrot** [comment]
OK, will do ASAP :)

**Comment by zulufoxtrot** [comment]
@cdnninja https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/139 :)

**Pull request closed without merging**
