### PR TITLE
(Kia EU) API Error handling + refactor

### PR DESCRIPTION
**Pull request by zulufoxtrot**
Continued work from https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/83

- Add API exceptions
- Perform API error handling
- Refactor: simplify headers
- Linting

Passed tests:
- cached request
- forced request
- stop climate
- stop charging

### CODE REVIEW

**Comment by cdnninja** [comment]
This is amazing work.   Really appreciate what you are doing.   I think this model is what will need to be done on USA and Canada in the future as well.   How do I convince you to join me over on the kia_uvo home assistant integration?

**Comment by zulufoxtrot** [comment]
Thanks! I hope I did not break anything :)

One question: what was the intended purpose of the "stage" argument in the exeption constructor of https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/83 ?

I just noticed one of my exception calls is without this argument, so it'll crash.

**Comment by zulufoxtrot** [comment]
> How do I convince you to join me over on the kia_uvo home assistant integration?

I don't know, how can I help? I don't use home assistant (for now ;).

**Comment by cdnninja** [comment]
> Thanks! I hope I did not break anything :)
> 
> 
> 
> One question: what was the intended purpose of the "stage" argument in the exeption constructor of https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/83 ?
> 
> 
> 
> I just noticed one of my exception calls is without this argument, so it'll crash.


Stage was from code I was using as a template. They used it as a way to pass details into the exceptions.   Such as stage of login.

**Pull request merged**
