### PR TITLE
fix: KiaUVOApiCA check_action_status

### PR DESCRIPTION
**Pull request by rjantoine**
Adds synchronicity (run until complete) and returns OrderStatus instead of simply returning True.

### CODE REVIEW

**Comment by rjantoine** [comment]
I have tested this and it works as expected.

vm.check_action_status(vehicle_id, action_id, False) only runs once and returns either OrderStatus.FAILED, SUCCESS or PENDING.

vm.check_action_status(vehicle_id, action_id, True, timeout) runs every 10 seconds until return status is OrderStatus.FAILED, SUCCESS or timeout is reached and returns TIMEOUT.

**Comment by cdnninja** [comment]
Awesome! I haven't looked at other regions.  I assume eu appears to have same behaviour?

**Comment by rjantoine** [comment]
Although it’s implemented differently, yes, this code behaves the same way as the EU check_action_status and the same way as specified in coordinator.

**Comment by cdnninja** [comment]
Thanks for confirming!

**Comment by rjantoine** [comment]
The only region that doesn’t behave this way is the US. BluelinkApiUS doesn’t even have a check_action_status.

KiaUvoApiUSA has check_action_status but it simply returns True. It does not have a synchronous option implemented and does not return the OrderStatus constants.

**Pull request merged**
